from __future__ import annotations

import json
import re

import httpx

from app.core.config import Settings
from app.schemas.cost import CostQuoteRequest, CostQuoteResponse, TransportMode
from app.services.shipping_rates import quote_sea_shipping_rate, quote_shipping_rate
from app.services.zai_client import ZAIClient


class CostAgent:
    def __init__(self, settings: Settings):
        self.settings = settings
        self.zai_client = ZAIClient(
            api_key=settings.z_ai_api_key,
            base_url=settings.z_ai_base_url,
            model=settings.z_ai_model,
        )

    async def quote(self, payload: CostQuoteRequest) -> CostQuoteResponse:
        mode = self._normalize_mode(payload.transport_mode)
        billable_weight = max(payload.weight_kg, payload.volumetric_weight_kg or payload.weight_kg)
        shipping_rate = quote_shipping_rate(payload.origin_region, billable_weight) if mode == "air" else quote_sea_shipping_rate(payload.origin_region, billable_weight)
        notes = ["Estimated values only. Confirm final customs and carrier charges before booking."]
        if shipping_rate is not None:
            if mode == "air":
                notes.append(
                    f"Hardcoded {shipping_rate.origin_region.value.title()} Malaysia AIR rate card applied ({shipping_rate.rate_band} pricing)."
                )
            else:
                notes.append(
                    f"Hardcoded {shipping_rate.origin_region.value.title()} Malaysia SEA LCL rate card applied ({shipping_rate.rate_band} pricing, min 20.0 kg)."
                )

        cost_values = self._deterministic_cost_values(payload=payload, mode=mode, billable_weight=billable_weight)
        if shipping_rate is not None:
            cost_values["shipping_fee"] = shipping_rate.shipping_fee
        used_zai = False

        if self.settings.z_ai_api_key:
            try:
                ai_values = await self._quote_with_zai(payload=payload, mode=mode, billable_weight=billable_weight)
                cost_values.update(ai_values)
                if shipping_rate is not None:
                    cost_values["shipping_fee"] = shipping_rate.shipping_fee
                used_zai = True
                notes.append("Cost components were generated by Z.ai Agent 3.")
            except (RuntimeError, ValueError, httpx.HTTPError, json.JSONDecodeError) as error:
                notes.append(f"Z.ai cost generation unavailable, fallback formula used: {error.__class__.__name__}.")

        required_documents = self._required_documents(mode)
        normalized_provided = self._normalize_documents(payload.provided_documents)
        missing_documents = [doc for doc in required_documents if doc not in normalized_provided]
        documents_ready = len(missing_documents) == 0

        if self.settings.umh_3_api_key:
            notes.append("UMH_3_API_KEY is configured for Agent 3.")
        if shipping_rate is not None:
            notes.append(f"Billable weight rounded to the nearest 0.5 kg band: {shipping_rate.rate_weight_kg} kg.")

        estimated_total_cost = round(
            cost_values["shipping_fee"]
            + cost_values["insurance_fee"]
            + cost_values["customs_duty"]
            + cost_values["import_tax"]
            + cost_values["documentation_fee"]
            + cost_values["customs_broker_fee"]
            + cost_values["port_handling_fee"],
            2,
        )

        return CostQuoteResponse(
            product_name=payload.product_name,
            destination_country=payload.destination_country,
            origin_region=shipping_rate.origin_region,
            transport_mode=mode,
            currency=payload.currency,
            billable_weight_kg=round(billable_weight, 2),
            shipping_rate_band=shipping_rate.rate_band,
            shipping_rate_weight_kg=shipping_rate.rate_weight_kg,
            shipping_fee=cost_values["shipping_fee"],
            insurance_fee=cost_values["insurance_fee"],
            customs_duty=cost_values["customs_duty"],
            import_tax=cost_values["import_tax"],
            documentation_fee=cost_values["documentation_fee"],
            customs_broker_fee=cost_values["customs_broker_fee"],
            port_handling_fee=cost_values["port_handling_fee"],
            estimated_total_cost=estimated_total_cost,
            required_documents=required_documents,
            missing_documents=missing_documents,
            documents_ready=documents_ready,
            notes=notes,
            export_pack={
                "stage": "agent_3",
                "ready_to_proceed": documents_ready,
                "shipping_mode": mode,
                "calculation_source": "z-ai" if used_zai else "formula",
                "document_count": int(len(normalized_provided)),
                "missing_document_count": int(len(missing_documents)),
            },
        )

    def _deterministic_cost_values(self, payload: CostQuoteRequest, mode: str, billable_weight: float) -> dict[str, float]:
        rate_per_kg = 7.5 if mode == "air" else 2.2
        minimum_shipping = 28.0 if mode == "air" else 55.0
        shipping_fee = round(max(minimum_shipping, billable_weight * rate_per_kg) * payload.package_count, 2)

        insurance_fee = round(payload.declared_value * payload.insurance_rate, 2)
        customs_duty = round(payload.declared_value * payload.duty_rate, 2)
        import_tax_base = payload.declared_value + shipping_fee + insurance_fee + customs_duty
        import_tax = round(import_tax_base * payload.tax_rate, 2)

        return {
            "shipping_fee": shipping_fee,
            "insurance_fee": insurance_fee,
            "customs_duty": customs_duty,
            "import_tax": import_tax,
            "documentation_fee": round(payload.documentation_fee, 2),
            "customs_broker_fee": round(payload.customs_broker_fee, 2),
            "port_handling_fee": round(payload.port_handling_fee, 2),
        }

    async def _quote_with_zai(self, payload: CostQuoteRequest, mode: str, billable_weight: float) -> dict[str, float]:
        system_prompt = (
            "You are a landed-cost calculator for Malaysia exports. Return valid JSON only with numeric fields: "
            "shipping_fee, insurance_fee, customs_duty, import_tax, documentation_fee, customs_broker_fee, port_handling_fee. "
            "Do not include markdown or extra keys."
        )

        prompt = (
            f"product_name={payload.product_name}\n"
            f"destination_country={payload.destination_country}\n"
            f"transport_mode={mode}\n"
            f"declared_value={payload.declared_value}\n"
            f"weight_kg={payload.weight_kg}\n"
            f"volumetric_weight_kg={payload.volumetric_weight_kg}\n"
            f"billable_weight_kg={billable_weight}\n"
            f"currency={payload.currency}\n"
            f"package_count={payload.package_count}\n"
            f"insurance_rate={payload.insurance_rate}\n"
            f"duty_rate={payload.duty_rate}\n"
            f"tax_rate={payload.tax_rate}\n"
            f"documentation_fee_default={payload.documentation_fee}\n"
            f"customs_broker_fee_default={payload.customs_broker_fee}\n"
            f"port_handling_fee_default={payload.port_handling_fee}\n"
            f"provided_documents={payload.provided_documents}\n"
        )

        raw = await self.zai_client.chat_json(system_prompt=system_prompt, user_prompt=prompt, temperature=0.0)

        parsed = self._parse_json_content(raw)
        return {
            "shipping_fee": self._float_field(parsed, "shipping_fee"),
            "insurance_fee": self._float_field(parsed, "insurance_fee"),
            "customs_duty": self._float_field(parsed, "customs_duty"),
            "import_tax": self._float_field(parsed, "import_tax"),
            "documentation_fee": self._float_field(parsed, "documentation_fee"),
            "customs_broker_fee": self._float_field(parsed, "customs_broker_fee"),
            "port_handling_fee": self._float_field(parsed, "port_handling_fee"),
        }

    def _parse_json_content(self, content: str) -> dict[str, object]:
        text = (content or "").strip()
        if not text:
            raise ValueError("Empty response from Z.ai")

        if text.startswith("```"):
            text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.IGNORECASE)
            text = re.sub(r"\s*```$", "", text)

        try:
            result = json.loads(text)
        except json.JSONDecodeError:
            match = re.search(r"\{[\s\S]*\}", text)
            if not match:
                raise
            result = json.loads(match.group(0))

        if not isinstance(result, dict):
            raise ValueError("Z.ai response is not a JSON object")
        return result

    def _float_field(self, data: dict[str, object], key: str) -> float:
        value = data.get(key)
        if value is None:
            raise ValueError(f"Missing field: {key}")
        number = float(value)
        if number < 0:
            raise ValueError(f"Negative value for field: {key}")
        return round(number, 2)

    def _normalize_mode(self, transport_mode: TransportMode) -> str:
        if transport_mode in {TransportMode.sea, TransportMode.ship}:
            return "sea"
        return "air"

    def _required_documents(self, mode: str) -> list[str]:
        common_documents = ["Commercial invoice", "Packing list"]
        if mode == "sea":
            return common_documents + ["Export declaration (K2)", "Shipping instruction", "Draft bill of lading"]
        return common_documents + ["Air waybill instructions", "HS code sheet"]

    def _normalize_documents(self, documents: list[str]) -> list[str]:
        return sorted({str(document).strip() for document in documents if str(document).strip()})
